leftnav:
- identifier: c263d9e5-6c9b-32d2-5206-c0045d2ed883
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 414d29a8-94c1-395e-73ef-33ec4600dc2b
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: e130e516-bd64-bf9f-6e82-c8cf300b6800
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 141e7b13-45b1-0456-3416-4c467c48896b
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: dd48d6de-c5a9-528a-90e5-514194ca72ee
  name: Projects
  pageRef: /pages/projects
  weight: 50
